name: first-workflow 
on: workflow_dispatch 
jobs: 
  first-job:
    runs-on: ubuntu-latest
    steps: 
      - name: print greeting 
        run: echo "hello-world" 
      - name: print message 
        run: echo "goodb bye" 
